#!/bin/sh
# postrm script for hfcldd

set -e
INSTLOG="/tmp/hfcldd_install.log"
case "$1" in
       purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        echo " ---- Uninstall  @Hitachi Fibre Channel Adapter Driver" >> $INSTLOG
	echo ""
	depmod -a
        echo " ---- Uninstall Success" >> $INSTLOG
        echo ""
	exit 0

        ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
esac
